title:              Wuzhe Xu
email:              wuzhexu@umass.edu
description:        Welcome to Wuzhe Xu's website
author:             Wuzhe Xu
baseurl:            ""
url:                "https://woodssss.github.io"

# Social Profiles
twitter_username:  https://www.researchgate.net/profile/Wuzhe-Xu 
github_username:     woodssss
linkedin_username:   wuzhe-xu-a0a7a3b1

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
